name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev mesa-utils ninja-build pkg-config
          
      # تثبيت إصدار Flutter 3.44.8 رسمياً ليكون متاحاً في المسار العام
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.8'
          channel: 'stable'
          
      # قبول التراخيص لنسخة فلاتر الرسمية
      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses
          
      - name: Install dependencies
        run: |
          pip install flet requests
          
      # بناء التطبيق مباشرة بعد تجهيز كل شيء
      - name: Build APK
        run: flet build apk
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VodafoneApp-APK
          path: build/apk/**/*.apk
