name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev mesa-utils ninja-build pkg-config
      
      # السر هنا: حددنا نفس الإصدار 3.24.3 اللي هو طالبه بالظبط
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          
      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses
          
      - name: Install dependencies
        run: |
          pip install flet requests
          
      # رجعنا أمر البناء سليم ونظيف من غير yes | لأنه خلاص مش هيسأل
      - name: Build APK
        run: flet build apk
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VodafoneApp-APK
          path: build/apk/**/*.apk
